# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b878e6be3dfd8d6381582987c4ad2cb2e3f0e25dd49ac816db2f2adf2b524019c7838b9a4aa3d1ae707a81ff3ee4f630f3a11440491e1c355bd1eb6d3c33368

test:
  secret_key_base: c124344d09f9a569ba50c2a5dd56e7fa975b971f227e40f7483251d529efdced5cf2de2c35b4b7471f52bdda36bc457bbf815a770a3839601ebc294e48e83f96

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
